[FEAT]: Add oracle db as an option in database connections (#442)
* feat(oracle): create new subtype of database

* feat(connections): add oracledb as an option in database connections

* fix(app): remove unnecessary code

* refactor(dockerfile): translate comments from PT-BR to EN

* refactor(oracledb): remove unecessary code and translate missing texts

* chore(version): update to version 1.25.0

diff --git a/Dockerfile.tools b/Dockerfile.tools
--- a/Dockerfile.tools
+++ b/Dockerfile.tools
@@ -10,43 +10,50 @@ ARG AWS_SM_VERSION=1.2.398.0
 RUN mkdir -p /app && \
     apt-get update -y && \
     apt-get install -y \
-        python3-dev \
-        python3-pip \
-        locales \
-        tini \
-        apt-utils \
-        curl \
-        gnupg \
-        gnupg2 \
-        net-tools \
-        netcat \
-        groff \
-        jq \
-        openssh-client \
-        unzip \
-        expect \
-        less \
-        gettext-base \
-        lsb-release && \
-        ln -s /usr/bin/python3 /usr/bin/python
+    python3-dev \
+    python3-pip \
+    locales \
+    tini \
+    apt-utils \
+    curl \
+    gnupg \
+    gnupg2 \
+    net-tools \
+    netcat \
+    groff \
+    jq \
+    openssh-client \
+    unzip \
+    expect \
+    less \
+    gettext-base \
+    lsb-release \
+    alien \
+    libaio1 \
+    elfutils \
+    libelf-dev \
+    bc \
+    wget \
+    && \
+    ln -s /usr/bin/python3 /usr/bin/python
 
 # kubectl / aws-cli / aws-session-manager
 RUN curl -sL "https://dl.k8s.io/release/v1.22.1/bin/linux/amd64/kubectl" -o kubectl && \
-        echo '78178a8337fc6c76780f60541fca7199f0f1a2e9c41806bded280a4a5ef665c9  kubectl' | sha256sum -c --ignore-missing --strict - && \
-        chmod 755 kubectl && \
-        mv kubectl /usr/local/bin/kubectl && \
+    echo '78178a8337fc6c76780f60541fca7199f0f1a2e9c41806bded280a4a5ef665c9  kubectl' | sha256sum -c --ignore-missing --strict - && \
+    chmod 755 kubectl && \
+    mv kubectl /usr/local/bin/kubectl && \
     curl -sL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-$AWS_CLI_VERSION.zip" -o awscli-exe-linux-x86_64-$AWS_CLI_VERSION.zip && \
-        echo '8f1de286d2c66cc0d0d26f205fdb17d5ed073f1e97f305c522e2d1fd89d5c854  awscli-exe-linux-x86_64-2.9.6.zip' | sha256sum \
-            -c --ignore-missing --strict - && \
-        unzip -q awscli-exe-linux-x86_64-$AWS_CLI_VERSION.zip && \
-        aws/install && \
-        aws --version && \
-        rm -rf aws && \
+    echo '8f1de286d2c66cc0d0d26f205fdb17d5ed073f1e97f305c522e2d1fd89d5c854  awscli-exe-linux-x86_64-2.9.6.zip' | sha256sum \
+    -c --ignore-missing --strict - && \
+    unzip -q awscli-exe-linux-x86_64-$AWS_CLI_VERSION.zip && \
+    aws/install && \
+    aws --version && \
+    rm -rf aws && \
     curl -sL "https://s3.amazonaws.com/session-manager-downloads/plugin/$AWS_SM_VERSION/ubuntu_64bit/session-manager-plugin.deb" -o session-manager-plugin.deb && \
-        echo 'aae58e58fcfbba465231086766d236ce8d032ae73b9335690e1faba704af2f9a  session-manager-plugin.deb' | sha256sum \
-            -c --ignore-missing --strict - && \
-        dpkg -i session-manager-plugin.deb && \
-        rm -rf /tmp/* session-manager-plugin.deb
+    echo 'aae58e58fcfbba465231086766d236ce8d032ae73b9335690e1faba704af2f9a  session-manager-plugin.deb' | sha256sum \
+    -c --ignore-missing --strict - && \
+    dpkg -i session-manager-plugin.deb && \
+    rm -rf /tmp/* session-manager-plugin.deb
 
 RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
     echo "deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list && \
@@ -61,16 +68,46 @@ RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" | tee /e
 
 RUN apt-get update -y && \
     apt-get install -y \
-        mongodb-mongosh mongodb-org-tools mongodb-org-shell \
-        openjdk-11-jre \
-        heroku \
-        default-mysql-client \
-        postgresql-client-15 \
-        sqlcmd \
-        unixodbc-dev \
-        google-cloud-cli=441.0.0-0 \
-        google-cloud-sdk-gke-gcloud-auth-plugin=441.0.0-0 && \
-        rm -rf /var/lib/apt/lists/*
+    mongodb-mongosh mongodb-org-tools mongodb-org-shell \
+    openjdk-11-jre \
+    heroku \
+    default-mysql-client \
+    postgresql-client-15 \
+    sqlcmd \
+    unixodbc-dev \
+    google-cloud-cli=441.0.0-0 \
+    google-cloud-sdk-gke-gcloud-auth-plugin=441.0.0-0 && \
+    rm -rf /var/lib/apt/lists/*
+
+# Download and install Oracle Instant Client and SQL*Plus
+RUN URL_ORACLE_BASIC= && URL_ORACLE_SQLPLUS= && dpkgArch="$(dpkg --print-architecture)" \
+    && case "${dpkgArch##*-}" in \
+    amd64) URL_ORACLE_BASIC='https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-basic-linux.x64-19.24.0.0.0dbru.zip';; \
+    arm64) URL_ORACLE_BASIC='https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linux-arm64.zip';; \
+    i386) URL_ORACLE_BASIC='https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-basic-linux-19.24.0.0.0dbru.zip';; \
+    *) echo "unsupported architecture"; exit 1 ;; \
+    esac \
+    && case "${dpkgArch##*-}" in \
+    amd64) URL_ORACLE_SQLPLUS='https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-sqlplus-linux.x64-19.24.0.0.0dbru.zip';; \
+    arm64) URL_ORACLE_SQLPLUS='https://download.oracle.com/otn_software/linux/instantclient/instantclient-sqlplus-linux-arm64.zip';; \
+    i386) URL_ORACLE_SQLPLUS='https://download.oracle.com/otn_software/linux/instantclient/1924000/instantclient-sqlplus-linux-19.24.0.0.0dbru.zip';; \
+    *) echo "unsupported architecture"; exit 1 ;; \
+    esac \
+    && mkdir -p /opt/oracle && \
+    cd /opt/oracle && \
+    wget -O instantclient-basic-linux.zip $URL_ORACLE_BASIC && \
+    wget -O instantclient-sqlplus-linux.zip $URL_ORACLE_SQLPLUS && \
+    unzip instantclient-basic-linux.zip && \
+    rm -rf META-INF && \
+    unzip instantclient-sqlplus-linux.zip && \
+    rm instantclient-basic-linux.zip && \
+    rm instantclient-sqlplus-linux.zip && \
+    echo 'set markup csv on delimiter "\t" quote off\nset heading on echo off termout off\nset feedback off trimspool on' >> instantclient_19_24/glogin.sql && \
+    cd /
+
+# Configure environment variables
+ENV PATH="/opt/oracle/instantclient_19_24:$PATH"
+ENV LD_LIBRARY_PATH="/opt/oracle/instantclient_19_24:$LD_LIBRARY_PATH"  
 
 # clojure
 RUN curl -sL https://download.clojure.org/install/linux-install-$CLOJURE_VERSION.sh -o clojure-install.sh && \
